source :rubygems

gem 'bundler'
gem 'riak-client', :path => "../riak-client"
gem 'activemodel', '3.1.0.beta1'
gem 'rspec', '~>2.4.0'
gem 'tzinfo'
gem 'rake'

platforms :mri do
  gem 'yajl-ruby'
end

platforms :jruby do
  gem 'json'
  gem 'jruby-openssl'
end
